/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wz1_rxjava2_ndk_NDKFileUtil */

#ifndef _Included_com_example_wz1_rxjava2_ndk_NDKFileUtil
#define _Included_com_example_wz1_rxjava2_ndk_NDKFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wz1_rxjava2_ndk_NDKFileUtil
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_wz1_rxjava2_ndk_NDKFileUtil_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_example_wz1_rxjava2_ndk_NDKFileUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_wz1_rxjava2_ndk_NDKFileUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
