/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wz1_rxjava2_ndk_MyNdk */

#ifndef _Included_com_example_wz1_rxjava2_ndk_MyNdk
#define _Included_com_example_wz1_rxjava2_ndk_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wz1_rxjava2_ndk_MyNdk
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wz1_rxjava2_ndk_MyNdk_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
